apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cost-exporter
  labels:
    app.kubernetes.io/component: pace
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aws-cost-exporter
  template:
    metadata:
      labels:
        name: aws-cost-exporter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
      serviceAccountName: aws-cost-exporter
      containers:
        - name: aws-cost-exporter
          image: ghcr.io/loafoe/prometheus-aws-cost-exporter:v0.0.6
          command: ["/usr/bin/prometheus-aws-cost-exporter"]
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 12001
            runAsGroup: 12001
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 20m
              memory: 256Mi
          volumeMounts:
            - mountPath: /etc/pace
              name: pace-configmap
      volumes:
        - name: pace-configmap
          configMap:
            name: pace-configmap
            items:
              - key: config.yaml
                path: config.yaml
