apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: ${RESOURCE_PREFIX}-pace-role
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Federated": "${OIDC_PROVIDER_ARN}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "${OIDC_PROVIDER}:aud": "sts.amazonaws.com",
                    "${OIDC_PROVIDER}:sub": "system:serviceaccount:finops-system:aws-cost-exporter"
                }
            }
          }
        ]
      }
    inlinePolicy:
      name: ce-access
      policy: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "ce:*"
              ],
              "Resource": "*"
            }
          ]
        }