apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- configmap.yaml
- iamrole.yaml
- serviceaccount.yaml
- servicemonitor.yaml
- service.yaml

namespace: finops-system
