apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-cost-exporter
  labels: 
    app.kubernetes.io/component: pace
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${RESOURCE_PREFIX}-pace-role
automountServiceAccountToken: true
