apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aws-cost-exporter
  namespace: finops-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-cost-exporter
  endpoints:
    - port: http-metrics
      path: /metrics
  namespaceSelector:
    matchNames:
      - finops-system